= Kubernetes - Setup Bastion Host for Development Environment
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images

This Step reference deployment guide provides instructions for deploying Linux bastion hosts in an Amazon Virtual Private Cloud environment on the Amazon Web Services (AWS) Cloud. The Step also provides AWS CloudFormation templates that automate the deployment.

The guide is for IT infrastructure architects, DevOps engineers, and administrators who are building an AWS Cloud environment for their workloads and would like to securely deploy Linux bastion hosts to manage their deployments remotely.

The following links are for your convenience. Before you launch the this Step, please review the architecture, configuration, and other considerations discussed in this guide.

If you have an AWS account and you’re already familiar with AWS services, you can launch the Quick Start to build the architecture shown in Figure 1 in a new or existing Amazon VPC in your AWS account. The deployment takes approximately 5 minutes. If you’re new to AWS, please follow the step-by-step instructions provided later in this guide.

:frame: none
:grid: none
:valign: top

|=====
|link:../../Launch-BH-withVPC.adoc[Go to Standard Index]
|link:../../launch-BH-existingVPC.adoc[Go to Developer Index]
|===

[NOTE]
If you want to take a look under the covers, you can view the AWS CloudFormation templates that automate the deployment. The templates include default settings that you can customize by following the instructions in this guide.
====
